api:
  version: "v1"

http:
  listener:
    basePath: "/a-flights-ea/api/${api.version}"
  requester:
    flightsAPI:
      basePath: "/a-flights-pa/api/v1"
    countryWeatherAPI:
      basePath: "/a-country-weather-pa/api/v1"

